---

- name: Make sure directories exist
  file:
    path: '{{ remote_path }}'
    state: directory
    directory_mode: yes

- name: Push image to remote
  copy:
    src: '{{ pull_path }}/{{ archive_name }}.tar'
    dest: '{{ remote_path }}/{{ archive_name }}.tar'
    directory_mode: yes

- name: Import docker tar image
  docker_image:
    name: '{{ image_name }}'
    load_path: '{{ remote_path }}/{{ archive_name }}.tar'
    state: present
    force: yes

- name: Copy the service template file
  template:
    src: redis-svc.yml.j2
    dest: "{{ remote_path }}/redis-svc.yml"

- name: Copy the deployment template file
  template:
    src: redis-dp.yml.j2
    dest: "{{ remote_path }}/redis-dp.yml"

- name: Deploy redis service
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/redis-svc.yml
  run_once: true

- name: Deploy redis deployment
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/redis-dp.yml
  run_once: true

