archive_name: els
git_repo: git@github.com:cloudtrust/elasticsearch-service.git
dockerfile: cloudtrust-elasticsearch.dockerfile

pull_path: '{{ role_path }}/elasticsearch'
dockerfile_path: '{{ pull_path }}/dockerfiles'
context: '{{ pull_path }}/build_context'
image_name: 'cloudtrust-elasticsearch:{{ config_name }}-{{ config_git_tag }}'

remote_path: /cloudtrust/elasticsearch
