---

- name: Deploy the cloudtrust base-image
  hosts: 127.0.0.1
  tasks:
    - name: Get that repo
      git:
        repo: '{{ git_repo }}'
        dest: '{{ playbook_dir }}/config'
        version: '{{ git_tag }}'
      tags: always

    - name: Deploy everything in deploy
      shell: rsync -a {{ playbook_dir }}/config/deployable/ {{ playbook_dir }}/
      register: msg
      tags: deploy

    - name: debug
      debug: msg={{ msg.stdout_lines }}
      tags: deploy

    - name: Clean config
      shell: for i in $(find {{ playbook_dir }}/config/deployable -type f); do rm -f {{ playbook_dir }}/${i#{{ playbook_dir }}/config/deployable/}; done
      tags: cleanup
