---

- name: Create remote directory
  file:
    path: "{{ remote_path }}"
    state: directory

- name: Deploy the kibana image
  copy:
    src: '{{ pull_path }}/{{ archive_name }}.tar'
    dest: '{{ remote_path }}/{{ archive_name }}.tar'
    
- name: Import docker tar image
  docker_image:
    name: '{{ image_name }}'
    load_path: '{{ remote_path }}/{{ archive_name }}.tar'
    state: present
    force: yes

- name: Deploy client configmap
  template:
    src: elasticsearch-client-cm.yml.j2
    dest: "{{ remote_path }}/elasticsearch-client-cm.yml"

- name: Deploy client deployment
  template:
    src: kibana-dp.yml.j2
    dest: "{{ remote_path }}/kibana-dp.yml"

- name: Deploy client configmap
  template:
    src: kibana-svc.yml.j2
    dest: "{{ remote_path }}/kibana-svc.yml"

- name: Deploy client tls keys
  template:
    src: kibana-tls.yml.j2
    dest: "{{ remote_path }}/kibana-tls.yml"

- name: Deploy client ingress
  template:
    src: kibana-ing.yml.j2
    dest: "{{ remote_path }}/kibana-ing.yml"


- name: Create svc
  shell: kubectl replace --force -f {{ remote_path }}/kibana-svc.yml
  run_once: true

- name: Create tls
  shell: kubectl replace --force -f {{ remote_path }}/kibana-tls.yml
  run_once: true

- name: Create 
  shell: kubectl replace --force -f {{ remote_path }}/kibana-ing.yml
  run_once: true

- name: Create configmap
  shell: kubectl replace --force -f {{ remote_path }}/elasticsearch-client-cm.yml
  run_once: true

- name: Create deployment
  shell: kubectl replace --force -f {{ remote_path }}/kibana-dp.yml
  run_once: true

