---
- name: Pull repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ pull_path }}'
    version: '{{ git_tag }}'

- name: Create build context
  file:
    path: '{{ context }}'
    state: directory

- name: Copy dockerfile to build context
  copy:
    src: '{{ dockerfile_path }}/{{ dockerfile }}'
    dest: '{{ context }}/Dockerfile'

- name: Build the image
  docker_image:
    name: '{{ image_name }}'
    path: '{{ context }}'
    state: present
    pull: False
    force: yes
    archive_path: '{{ context }}/{{ archive_name }}.tar'
    nocache: "{{ force | default('no') }}"
    buildargs:
      config_env: '{{ config_env }}'
      config_git_tag: '{{ config_branch }}'
      config_repo: '{{ config_repository }}'
      sentry_service_git_tag: '{{ git_tag }}'

