---
- name: Pull repository
  git:
    repo: '{{ git_repo }}'
    dest: '{{ pull_path }}'
    version: '{{ git_tag }}'

- name: Create build context
  file:
    path: '{{ context }}'
    state: directory

- name: Copy dockerfile to build context
  copy:
    src: '{{ dockerfile_path }}/{{ dockerfile }}'
    dest: '{{ context }}/Dockerfile'

- name: Build the image
  docker_image:
    name: '{{ image_name }}'
    path: '{{ context }}'
    pull: False
    nocache: "{{ force | default('no') }}"
    force: yes
    state: present
    buildargs:
      sentry_service_git_tag: '{{ git_tag }}'

- name: Copy config dockerfile to build context
  copy:
    src: '{{ dockerfile_path }}/{{ config_dockerfile }}'
    dest: '{{ context }}/Dockerfile'

- name: Build the config_image
  docker_image:
    name: '{{ config_image_name }}'
    path: '{{ context }}'
    pull: False
    state: present
    nocache: yes
    force: yes
    archive_path: '{{ context }}/{{ archive_name }}.tar'
    buildargs:
      environment: '{{ config_env }}'
      branch: '{{ config_branch }}'
      config_repository: '{{ config_repository }}'
      sentry_service_git_tag: '{{ git_tag }}'
