---
- name: Make sure directories exist
  file:
    path: '{{ remote_path }}'
    state: directory
    directory_mode: yes
  tags: deploy

- name: Push image to remote
  copy:
    src: '{{ context }}/{{ archive_name }}.tar'
    dest: '{{ remote_path }}/{{ archive_name }}.tar'
    directory_mode: yes
  tags: deploy

- name: Import docker tar image
  docker_image:
    name: '{{ image_name }}'
    load_path: '{{ remote_path }}/{{ archive_name }}.tar'
    state: present
    force: yes

- name: Copy the service template file
  template:
    src: sentry-svc.yml.j2
    dest: "{{ remote_path }}/sentry-svc.yml"

- name: Copy the ingress template file
  template:
    src: sentry-ing.yml.j2
    dest: "{{ remote_path }}/sentry-ing.yml"

- name: Copy the deployment template file
  template:
    src: sentry-dp.yml.j2
    dest: "{{ remote_path }}/sentry-dp.yml"

    
- name: Deploy sentry service
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/sentry-svc.yml
  run_once: true

- name: Deploy sentry ingress
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/sentry-ing.yml
  run_once: true

- name: Deploy sentry deployment
  shell: kubectl --kubeconfig={{ kubeconfig }} replace --force -f {{ remote_path }}/sentry-dp.yml
  run_once: true
