---
- name: Kubelet
  include_tasks: kubelet.yml
  tags: kubelet, deploy

- name: Apiserver
  include_tasks: apiserver.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-master'] }}"
  tags: apiserver, deploy

- name: Deploy admin access token
  include_tasks: tokens.yml
  tags: tokens, deploy
  
- name: Controller Manager
  include_tasks: controller-manager.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-master'] }}"
  tags: controller-manager, deploy

- name: Scheduler
  include_tasks: scheduler.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-master'] }}"
  tags: scheduler, deploy

- name: Kube-Proxy
  include_tasks: kube-proxy.yml
  tags: kube-proxy, deploy

- name: Startup the cluster
  include_tasks: start_kubernetes.yml
  tags: start, deploy

- name: Wait for kubernetes to be up
  include_tasks: start_wait.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-master'] }}"
  tags: start, deploy

- name: Prepare dns dirs
  include_tasks: kube-addon.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-master'] }}"
  tags: addons, deploy

- name: Install DNS
  include_tasks: kube-dns.yml
  delegate_to: "{{ item }}"
  with_items: "{{ groups['kube-master'][0] }}"
  run_once: true
  tags: addons, dns, deploy
