---

- name: Create and generate ceph keys
  include_tasks: create_keys.yml
  delegate_to: 127.0.0.1
  tags: create_keys, build

- name: Install Ceph on the nodes
  shell: dnf -y install ceph
  tags: deploy, common

- name: Create remote directory
  file:
    path: "{{ remote_path }}"
    state: directory
  tags: deploy, common

- name: Deploy namespace template
  include_tasks: deploy_namespace.yml
  tags: deploy, common

# Monitor
- name: Build the docker monitor image
  include_tasks: build_mon.yml
  delegate_to: 127.0.0.1
  run_once: true
  tags: build, mon

- name: Deploy ceph monitor 
  include_tasks: deploy_mon.yml
  tags: deploy, mon

# OSD
- name: Build the docker osd image
  include_tasks: build_osd.yml
  delegate_to: 127.0.0.1
  tags: build, osd

- name: Deploy ceph osd 
  include_tasks: deploy_osd.yml
  tags: deploy, osd

# Cleanup

- name: Clean pulled directories
  file:
    path: '{{ pull_path }}'
    state: 'absent'
  tags: cleanup

